In [8]:
q = ""
for a in range(0, 80):
    q += 'surv.a{:02d} AS "c2_A{:02d}",\n'.format(a, a)
    
q += 'surv.A80+ AS "c2_A80+",\n'
q += 'surv.unbekannt AS "c2_AUnbekannt",\n'
print(q)

surv.a00 AS "c2_A00",
surv.a01 AS "c2_A01",
surv.a02 AS "c2_A02",
surv.a03 AS "c2_A03",
surv.a04 AS "c2_A04",
surv.a05 AS "c2_A05",
surv.a06 AS "c2_A06",
surv.a07 AS "c2_A07",
surv.a08 AS "c2_A08",
surv.a09 AS "c2_A09",
surv.a10 AS "c2_A10",
surv.a11 AS "c2_A11",
surv.a12 AS "c2_A12",
surv.a13 AS "c2_A13",
surv.a14 AS "c2_A14",
surv.a15 AS "c2_A15",
surv.a16 AS "c2_A16",
surv.a17 AS "c2_A17",
surv.a18 AS "c2_A18",
surv.a19 AS "c2_A19",
surv.a20 AS "c2_A20",
surv.a21 AS "c2_A21",
surv.a22 AS "c2_A22",
surv.a23 AS "c2_A23",
surv.a24 AS "c2_A24",
surv.a25 AS "c2_A25",
surv.a26 AS "c2_A26",
surv.a27 AS "c2_A27",
surv.a28 AS "c2_A28",
surv.a29 AS "c2_A29",
surv.a30 AS "c2_A30",
surv.a31 AS "c2_A31",
surv.a32 AS "c2_A32",
surv.a33 AS "c2_A33",
surv.a34 AS "c2_A34",
surv.a35 AS "c2_A35",
surv.a36 AS "c2_A36",
surv.a37 AS "c2_A37",
surv.a38 AS "c2_A38",
surv.a39 AS "c2_A39",
surv.a40 AS "c2_A40",
surv.a41 AS "c2_A41",
surv.a42 AS "c2_A42",
surv.a43 AS "c2_A43",
surv.a44 AS "c2_A44",
surv.a45 AS "c2_A45",
surv.a46 AS "c2_A46",
surv.a47 AS "c2_A47",
surv.a48 AS "c2_A48",
surv.a49 AS "c2_A49",
surv.a50 AS "c2_A50",
surv.a51 AS "c2_A51",
surv.a52 AS "c2_A52",
surv.a53 AS "c2_A53",
surv.a54 AS "c2_A54",
surv.a55 AS "c2_A55",
surv.a56 AS "c2_A56",
surv.a57 AS "c2_A57",
surv.a58 AS "c2_A58",
surv.a59 AS "c2_A59",
surv.a60 AS "c2_A60",
surv.a61 AS "c2_A61",
surv.a62 AS "c2_A62",
surv.a63 AS "c2_A63",
surv.a64 AS "c2_A64",
surv.a65 AS "c2_A65",
surv.a66 AS "c2_A66",
surv.a67 AS "c2_A67",
surv.a68 AS "c2_A68",
surv.a69 AS "c2_A69",
surv.a70 AS "c2_A70",
surv.a71 AS "c2_A71",
surv.a72 AS "c2_A72",
surv.a73 AS "c2_A73",
surv.a74 AS "c2_A74",
surv.a75 AS "c2_A75",
surv.a76 AS "c2_A76",
surv.a77 AS "c2_A77",
surv.a78 AS "c2_A78",
surv.a79 AS "c2_A79",
surv.a80+ AS "c2_A80+",
surv.unbekannt AS "c2_AUnbekannt",

In [17]:
import loadenv
import os
import db
import pandas as pd
import pandas.io.sql as sqlio
from db import get_connection

In [ ]:
conn, cur = get_connection()

dat = sqlio.read_sql_query("""
SELECT ags, age, SUM(population)
FROM population_zensus
GROUP BY ags, age
ORDER BY ags, age
""", conn)


for _, row in dat.iterrows():
    d = row.to_dict()
    
    if d['age'] == 0:
        cur.execute(f"INSERT INTO population_survstat_agegroup (ags, a00) VALUES ({'{:05d}'.format(int(d['ags']))}, {d['sum']})")
    elif d['age'] > 0 and d['age'] < 80:
        cur.execute(f"UPDATE population_survstat_agegroup SET {'a{:02d}'.format(int(d['age']))} = {d['sum']} WHERE ags = '{'{:05d}'.format(int(d['ags']))}'")
        
conn.commit()

create table population_survstat_agegroup
(
    ags       varchar not null
        constraint population_survstat_agegroup_pk
            primary key,
    "A00-A04" integer,
    "A05-A14" integer,
    "A15-A34" integer,
    "A35-A59" integer,
    "A60-A79" integer,
    "A80+"    integer,
    name      varchar
);

In [20]:



q = ""
for a in range(0, 80):
    q += 'a{:02d} integer,\n'.format(a)
    
q += '"A80+" integer,\n'
q += 'unbekannt integer,\n'

print(q)

a00 integer,
a01 integer,
a02 integer,
a03 integer,
a04 integer,
a05 integer,
a06 integer,
a07 integer,
a08 integer,
a09 integer,
a10 integer,
a11 integer,
a12 integer,
a13 integer,
a14 integer,
a15 integer,
a16 integer,
a17 integer,
a18 integer,
a19 integer,
a20 integer,
a21 integer,
a22 integer,
a23 integer,
a24 integer,
a25 integer,
a26 integer,
a27 integer,
a28 integer,
a29 integer,
a30 integer,
a31 integer,
a32 integer,
a33 integer,
a34 integer,
a35 integer,
a36 integer,
a37 integer,
a38 integer,
a39 integer,
a40 integer,
a41 integer,
a42 integer,
a43 integer,
a44 integer,
a45 integer,
a46 integer,
a47 integer,
a48 integer,
a49 integer,
a50 integer,
a51 integer,
a52 integer,
a53 integer,
a54 integer,
a55 integer,
a56 integer,
a57 integer,
a58 integer,
a59 integer,
a60 integer,
a61 integer,
a62 integer,
a63 integer,
a64 integer,
a65 integer,
a66 integer,
a67 integer,
a68 integer,
a69 integer,
a70 integer,
a71 integer,
a72 integer,
a73 integer,
a74 integer,
a75 integer,
a76 integer,
a77 integer,
a78 integer,
a79 integer,
"A80+" integer,
unbekannt integer,